// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7wlR6nF_awb1NojHwiGudTBSQF4WdHU8',
    appId: '1:172131937774:web:c27e91663fef011d2eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    authDomain: 'fynxfit.firebaseapp.com',
    storageBucket: 'fynxfit.firebasestorage.app',
    measurementId: 'G-3KX42V5B09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyihQzGF_EYXSdky84x2k-_4Thnw4l440',
    appId: '1:172131937774:android:8ecc4908bd24d6a02eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    storageBucket: 'fynxfit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnYggzdQH4WnaQ5Dp_nFgCarg0SjtAMOs',
    appId: '1:172131937774:ios:a257ce30d5079aee2eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    storageBucket: 'fynxfit.firebasestorage.app',
    iosBundleId: 'com.example.fynxfituser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnYggzdQH4WnaQ5Dp_nFgCarg0SjtAMOs',
    appId: '1:172131937774:ios:a257ce30d5079aee2eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    storageBucket: 'fynxfit.firebasestorage.app',
    iosBundleId: 'com.example.fynxfituser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7wlR6nF_awb1NojHwiGudTBSQF4WdHU8',
    appId: '1:172131937774:web:beaea7e34ebf97672eb2ff',
    messagingSenderId: '172131937774',
    projectId: 'fynxfit',
    authDomain: 'fynxfit.firebaseapp.com',
    storageBucket: 'fynxfit.firebasestorage.app',
    measurementId: 'G-FPVL1XSMMS',
  );

}